services:
  opentelemetrydemo:
    image: opentelemetrydemo
    build:
      context: .
      dockerfile: OpenTelemetryDemo/Dockerfile
    ports:
      - 8080:8080
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetrydemo.dashboard:18889
    networks:
      - otel
      
  opentelemetrydemo.dashboard:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest
    container_name: dashboard
    ports:
      - 18888:18888
    networks:
      - otel
        
networks:
  otel: